// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAlbumCover(arg1) {
  return window['go']['main']['App']['GetAlbumCover'](arg1);
}

export function GetRandomAlbums() {
  return window['go']['main']['App']['GetRandomAlbums']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}
