// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAlbumCover(arg1:string):Promise<Array<number>>;

export function GetRandomAlbums():Promise<Array<main.Album>>;

export function Greet(arg1:string):Promise<string>;

export function LoadRandomAlbums():Promise<void>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<boolean>;
